#!/usr/bin/env bash
# OpenAdKit one-line installer for macOS / Linux / WSL
# Usage from any terminal:
#   curl -fsSL https://raw.githubusercontent.com/IamRamgarhia/OpenAdKit-Open-Source-AI-Marketing-Tool/main/install-online.sh | bash
#
# Does everything in one go:
#   1. Checks for Node.js + git (suggests install command if missing)
#   2. Clones OpenAdKit into ~/OpenAdKit
#   3. Runs npm install
#   4. Prompts for port (default 3005)
#   5. Launches the launcher control panel in your browser

set -e

REPO="https://github.com/IamRamgarhia/OpenAdKit-Open-Source-AI-Marketing-Tool.git"
BRANCH="main"
TARGET="${ADFORGE_DIR:-$HOME/OpenAdKit}"

c_cyan="\033[36m"; c_green="\033[32m"; c_yellow="\033[33m"; c_red="\033[31m"; c_reset="\033[0m"
step()  { printf "\n${c_cyan}==> %s${c_reset}\n" "$1"; }
ok()    { printf "${c_green}OK  %s${c_reset}\n" "$1"; }
warn()  { printf "${c_yellow}!!  %s${c_reset}\n" "$1"; }
err()   { printf "${c_red}ERR %s${c_reset}\n" "$1"; }

echo
echo "=================================================="
echo " OpenAdKit installer - by Dicecodes"
echo "=================================================="

# --- Detect OS for install hints ---
OS="$(uname -s)"
hint_install_node=""
hint_install_git=""
case "$OS" in
    Darwin)
        hint_install_node="brew install node"
        hint_install_git="brew install git"
        ;;
    Linux)
        if   command -v apt-get >/dev/null 2>&1; then
            hint_install_node="sudo apt-get update && sudo apt-get install -y nodejs npm"
            hint_install_git="sudo apt-get install -y git"
        elif command -v dnf >/dev/null 2>&1; then
            hint_install_node="sudo dnf install -y nodejs npm"
            hint_install_git="sudo dnf install -y git"
        elif command -v pacman >/dev/null 2>&1; then
            hint_install_node="sudo pacman -S nodejs npm"
            hint_install_git="sudo pacman -S git"
        else
            hint_install_node="(use your distro's package manager to install Node 20+)"
            hint_install_git="(use your distro's package manager to install git)"
        fi
        ;;
    *)
        hint_install_node="install Node 20+ from https://nodejs.org/en/download"
        hint_install_git="install git from https://git-scm.com/downloads"
        ;;
esac

# --- Step 1: Node ---
step "Checking for Node.js"
if ! command -v node >/dev/null 2>&1; then
    err "Node.js not found."
    echo "  Install it with:  $hint_install_node"
    echo "  Then re-run this installer."
    exit 1
fi
ok "Node $(node --version)"

# --- Step 2: Git ---
step "Checking for git"
if ! command -v git >/dev/null 2>&1; then
    err "git not found."
    echo "  Install it with:  $hint_install_git"
    echo "  Then re-run this installer."
    exit 1
fi
ok "$(git --version)"

# --- Step 3: Clone ---
step "Fetching OpenAdKit into $TARGET"
if [ -d "$TARGET/.git" ]; then
    echo "Existing checkout found. Pulling latest..."
    (cd "$TARGET" && git pull --ff-only) || warn "git pull failed; continuing with existing files."
elif [ -d "$TARGET" ]; then
    warn "$TARGET exists and is not a git repo. Using folder as-is."
else
    git clone --depth=1 --branch "$BRANCH" "$REPO" "$TARGET"
fi
cd "$TARGET"
ok "Source ready at $TARGET"

# --- Step 4: npm install ---
step "Installing dependencies (first run can take a few minutes)"
npm install --no-audit --no-fund
ok "Dependencies installed"

# --- Step 5: Pick a port ---
step "Choose a port for the web app"
echo "Common ports: 3000, 3005, 4000, 8080. Press Enter for 3005."
PORT="3005"
if [ -f .env.local ]; then
    EXISTING=$(grep -E '^PORT=' .env.local | head -1 | cut -d= -f2 | tr -d '\r')
    [ -n "$EXISTING" ] && PORT="$EXISTING" && echo "Found existing PORT=$PORT in .env.local"
fi

# Read from /dev/tty so prompt works when script is piped from curl
if [ -t 0 ]; then
    read -r -p "Port [$PORT]: " USERPORT || USERPORT=""
else
    if [ -e /dev/tty ]; then
        read -r -p "Port [$PORT]: " USERPORT </dev/tty || USERPORT=""
    fi
fi
[ -n "$USERPORT" ] && PORT="$USERPORT"

# Validate
if ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
    warn "Not a number. Using 3005."
    PORT="3005"
elif [ "$PORT" -lt 1024 ] || [ "$PORT" -gt 65535 ]; then
    warn "Port out of range. Using 3005."
    PORT="3005"
fi

cat > .env.local <<EOF
# OpenAdKit configuration (generated by install-online.sh)
PORT=$PORT
ADFORGE_SYNC_PORT=3006
# Browser-visible mirror of ADFORGE_SYNC_PORT. Next only inlines NEXT_PUBLIC_*
# names into the client bundle, and the web app needs the sidecar port to reach
# it at all. Keep the two in lockstep. See lib/sync-endpoint.ts.
NEXT_PUBLIC_ADFORGE_SYNC_PORT=3006
EOF
mkdir -p data
ok "Saved PORT=$PORT to .env.local"

# --- Step 6: Launch ---
echo
echo "=================================================="
printf "${c_green} Install complete - launching OpenAdKit...${c_reset}\n"
echo "=================================================="
echo
echo "  Launcher (control panel): http://127.0.0.1:3006/"
echo "  Web app (after Start):    http://localhost:$PORT/"
echo
echo "  Click 'Start OpenAdKit' in the launcher when it opens."
echo "  Press Ctrl+C in this window or run  bash scripts/stop.sh  to shut down."
echo

open_url() {
    local url="$1"
    if   command -v open       >/dev/null 2>&1; then open "$url" &
    elif command -v xdg-open   >/dev/null 2>&1; then xdg-open "$url" &
    elif command -v wslview    >/dev/null 2>&1; then wslview "$url" &
    else echo "(open this URL manually: $url)"
    fi
}
( sleep 2 && open_url "http://127.0.0.1:3006/" ) &

trap 'echo; echo "Stopping OpenAdKit..."; exit 0' INT TERM
ADFORGE_SYNC_PORT=3006 node scripts/local-sync.cjs
