# OpenAdKit is free + MIT-licensed.
# We make money from custom builds at Dicecodes, not sponsorships.
# If you want to support development, the most useful things you can do are:
#   1. Star the repo (visibility signal)
#   2. Open thoughtful issues
#   3. Send a PR (see CONTRIBUTING.md)
#   4. Hire Dicecodes for a custom build — https://dicecodes.com

custom: ["https://dicecodes.com"]
