import { emptyBrandBrain, type BrandBrain } from "./brand-brain";

export interface IndustryTemplate {
  slug: string;
  name: string;
  emoji: string;
  description: string;
  apply: (override: { business_name?: string; website_url?: string }) => BrandBrain;
}

function makeBrain(override: { business_name?: string; website_url?: string }, partial: Partial<BrandBrain>): BrandBrain {
  const base = emptyBrandBrain();
  return {
    ...base,
    business_name: override.business_name || partial.business_name || "Your Brand",
    website_url: override.website_url || "",
    name: override.business_name || partial.business_name || "Your Brand",
    ...partial,
  } as BrandBrain;
}

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    slug: "local_restaurant",
    name: "Local restaurant / café",
    emoji: "🍽",
    description: "Sit-down or quick-service. Foot traffic + delivery + Instagram-worthy moments.",
    apply: (o) => makeBrain(o, {
      industry: "Food & beverage / hospitality",
      tone: "Warm, generous, neighborhood-feel — not corporate.",
      writing_style: "Short, sensory, present-tense. Verbs about taste + craft.",
      audience_who: "Locals within 5 miles, food-curious 25-55, weekday lunch + weekend dinner.",
      audience_pain_points: ["Limited time for lunch", "Tired of chain options", "Want something memorable for date night"],
      audience_desires: ["Discover their next favorite spot", "Eat well without thinking", "Share Instagram-worthy moments"],
      key_benefits: ["Fresh, local-sourced ingredients", "Family-recipe authenticity", "Friendly + fast service"],
      price_positioning: "mid-tier (premium ingredients without fine-dining price)",
      personality_traits: ["welcoming", "passionate", "rooted in the neighborhood"],
      words_to_use: ["fresh", "house-made", "locally sourced", "today", "tonight"],
      words_to_avoid: ["world-class", "best", "fine dining"],
      best_performing_angles: ["chef's-table behind-the-scenes", "ingredient origin stories", "limited-time daily specials"],
    }),
  },
  {
    slug: "b2b_saas",
    name: "B2B SaaS",
    emoji: "💼",
    description: "Sell to other companies. Long sales cycle. ROI + integrations matter more than features.",
    apply: (o) => makeBrain(o, {
      industry: "B2B SaaS",
      tone: "Confident, specific, outcome-led. No buzzwords.",
      writing_style: "Lead with the metric or named customer. Then say how.",
      audience_who: "Mid-market companies (50-500 employees), specific role (VP / Director / Head of X), $1M-$50M revenue.",
      audience_pain_points: ["Manual processes eating 10+ hours/week", "Tools that don't talk to each other", "Painful pricing creep on incumbents"],
      audience_desires: ["Hit the quarter target", "Replace a more expensive tool", "Look smart in front of leadership"],
      key_benefits: ["Cuts task X from 4 hours → 8 minutes", "Native integrations with stack they already have", "Implementation in days, not months"],
      price_positioning: "value (10× cheaper than enterprise alternative)",
      personality_traits: ["serious about ROI", "engineering-led", "transparent about pricing"],
      words_to_use: ["specifically", "in 8 minutes", "Acme uses this to…", "ROI"],
      words_to_avoid: ["leverage", "synergy", "transform", "world-class", "innovative"],
      objections: ["We tried this 3 years ago", "Our IT won't approve", "We don't have budget this quarter"],
      objection_handling: ["What changed: native integrations + 10× cheaper", "SOC 2 + named compliance officer", "Pay monthly, cancel anytime, ROI in 30 days"],
      best_performing_angles: ["specific time-saved quote from named customer", "before/after workflow demo", "head-to-head vs incumbent"],
    }),
  },
  {
    slug: "ecommerce_fashion",
    name: "E-commerce — fashion / apparel",
    emoji: "👗",
    description: "DTC fashion / accessories. Highly visual. Returns + sizing are top friction.",
    apply: (o) => makeBrain(o, {
      industry: "Fashion DTC",
      tone: "Confident, aspirational, slightly editorial.",
      writing_style: "Short. Visual. Reads like a magazine pull-quote.",
      audience_who: "25-44 urban, style-conscious, values quality + sustainability over fast fashion.",
      audience_pain_points: ["Inconsistent sizing across brands", "Worried about quality at this price", "Fed up with fast-fashion guilt"],
      audience_desires: ["Look effortlessly put-together", "Wear something with a story", "Stand out without trying"],
      key_benefits: ["True-to-size — 95% keep on first order", "Made in [country], in small batches", "Free returns, no questions"],
      price_positioning: "premium but not luxury",
      personality_traits: ["confident", "quality-obsessed", "low-key sustainable"],
      words_to_use: ["made in", "small-batch", "true-to-size", "shop the look"],
      words_to_avoid: ["best ever", "must-have", "exclusive deal"],
      best_performing_angles: ["before/after fit", "creator unboxing", "behind-the-scenes craft", "true-to-size guarantee"],
    }),
  },
  {
    slug: "local_service",
    name: "Local services (plumber / dentist / lawyer)",
    emoji: "🔧",
    description: "Service-area business. Reviews + trust + emergency-readiness drive bookings.",
    apply: (o) => makeBrain(o, {
      industry: "Local services",
      tone: "Reassuring, professional, no-jargon.",
      writing_style: "Short. Direct. Names the problem and the fix.",
      audience_who: "Homeowners + small business owners in service area, 30-65, value reliability over price.",
      audience_pain_points: ["Worried about being overcharged", "Bad past experiences with contractors", "Need it fixed today, not next week"],
      audience_desires: ["Trustworthy pro who shows up on time", "Upfront pricing, no surprises", "Fixed right the first time"],
      key_benefits: ["Same-day service available", "Upfront flat-rate quote", "Licensed + insured + 5-star reviews"],
      price_positioning: "fair (not cheapest, not most expensive)",
      personality_traits: ["reliable", "experienced", "neighborly"],
      words_to_use: ["same-day", "upfront pricing", "licensed", "no surprises"],
      words_to_avoid: ["cheapest", "deals", "discount"],
      best_performing_angles: ["named-customer testimonial with their problem", "before/after photo", "behind-the-scenes service moment"],
    }),
  },
  {
    slug: "consumer_app",
    name: "B2C app / SaaS",
    emoji: "📱",
    description: "Mobile-first consumer product. Acquisition through paid social + organic.",
    apply: (o) => makeBrain(o, {
      industry: "Consumer SaaS / app",
      tone: "Friendly, energetic, lightly contrarian.",
      writing_style: "Punchy, first-person, often a question or pattern interrupt.",
      audience_who: "18-35 urban, productivity-curious or wellness-curious, downloads + tries lots of apps.",
      audience_pain_points: ["Tried 5 apps for X and none stuck", "Feels overwhelmed by too many options", "Frustrated with subscriptions piling up"],
      audience_desires: ["Finally fix the thing they've been meaning to", "Show off the change to friends", "Feel like they have it together"],
      key_benefits: ["Built for people who don't have hours to spend", "Works in 5 minutes/day", "Free trial, cancel anytime"],
      price_positioning: "freemium",
      personality_traits: ["sharp", "encouraging", "honest about effort required"],
      words_to_use: ["5 minutes/day", "actually works", "no streak guilt", "delete the other 4"],
      words_to_avoid: ["revolutionize", "transform your life", "best app"],
      best_performing_angles: ["I tried X for 30 days", "POV: you finally", "stop scrolling if you have ADHD"],
    }),
  },
  {
    slug: "course_creator",
    name: "Course creator / coach",
    emoji: "🎓",
    description: "Knowledge product. Email list + webinar + cohort launches.",
    apply: (o) => makeBrain(o, {
      industry: "Education / coaching",
      tone: "Authoritative, story-led, personal.",
      writing_style: "First-person, anecdotal, builds tension before reveal.",
      audience_who: "Adult professionals 25-55 trying to upskill, side-hustle, or career-change.",
      audience_pain_points: ["Spent thousands on courses they didn't finish", "Tired of generic YouTube advice", "Stuck at a plateau they can't break alone"],
      audience_desires: ["Concrete framework to follow", "Community of peers further along", "Career-changing skill in 90 days"],
      key_benefits: ["Battle-tested over X cohorts with Y graduates", "Founder personally reviews student work", "Lifetime access + community"],
      price_positioning: "premium (high-ticket)",
      personality_traits: ["been there", "doesn't sell hype", "high standards"],
      words_to_use: ["framework", "what actually works", "the system I use", "after teaching 1,200 people"],
      words_to_avoid: ["secret", "hack", "guru", "make 6 figures"],
      best_performing_angles: ["founder origin story", "named student transformation", "controversial industry take"],
    }),
  },
  {
    slug: "agency",
    name: "Agency / consultancy",
    emoji: "🏢",
    description: "Sell expertise + done-for-you services. Referrals + case studies drive deals.",
    apply: (o) => makeBrain(o, {
      industry: "Agency / professional services",
      tone: "Confident, results-led, founder-voice.",
      writing_style: "Story-led. Open with a client outcome. Close with a soft CTA.",
      audience_who: "Founders + heads of marketing at $1M-$50M companies, time-poor, ROI-driven.",
      audience_pain_points: ["In-house team can't execute fast enough", "Burned by previous agencies", "Need senior strategy, not just execution"],
      audience_desires: ["Get the results an in-house hire would take 6 months to deliver", "Partner who thinks 5 steps ahead", "Predictable, audit-able process"],
      key_benefits: ["Senior-level strategy + execution", "Named outcomes from named clients", "Weekly working sessions, not monthly slides"],
      price_positioning: "premium retainer",
      personality_traits: ["senior", "outcome-obsessed", "transparent about what we don't do"],
      words_to_use: ["working with", "shipped", "after 90 days", "the kind of agency that"],
      words_to_avoid: ["best in class", "world-class", "thought leader"],
      best_performing_angles: ["named-client case study", "controversial industry take", "behind-the-process content"],
    }),
  },
  {
    slug: "info_product",
    name: "Info product / digital download",
    emoji: "📦",
    description: "Ebook, template, swipe file, course toolkit. Single price, single hook.",
    apply: (o) => makeBrain(o, {
      industry: "Info product / digital",
      tone: "Punchy, specific, one-promise-only.",
      writing_style: "Short. Specific. Stat-led.",
      audience_who: "Specialists in a niche role, drowning in scattered resources, ready to pay for shortcut.",
      audience_pain_points: ["Have to assemble this from 50 blog posts", "Spent 20 hours and still don't have it right", "Resentment of generic templates"],
      audience_desires: ["Done-for-them template they can ship today", "Looks like a senior-level deliverable", "Time saved"],
      key_benefits: ["Ready to use in 10 minutes", "Updated every 6 months", "Based on N companies / N campaigns / N years"],
      price_positioning: "value (high-volume, low-friction)",
      personality_traits: ["practical", "ruthlessly specific", "no fluff"],
      words_to_use: ["ready in 10 min", "swipe file", "I personally use this", "battle-tested"],
      words_to_avoid: ["secret", "ultimate guide", "everything you need"],
      best_performing_angles: ["before/after the template", "I made this for myself first", "specific time-saved math"],
    }),
  },
  {
    slug: "marketplace",
    name: "Marketplace / two-sided",
    emoji: "🛒",
    description: "Connects supply + demand. Different copy for each side.",
    apply: (o) => makeBrain(o, {
      industry: "Marketplace",
      tone: "Side-specific. Helpful to one, salesy to the other.",
      writing_style: "Always lead with which side you're talking to.",
      audience_who: "Supply side (sellers/providers) AND demand side (buyers) — completely different language for each.",
      audience_pain_points: ["Sellers: low platform fees + reliable buyers", "Buyers: trust + quality + speed"],
      audience_desires: ["Sellers: predictable income, fewer no-shows", "Buyers: vetted options, no surprises"],
      key_benefits: ["Vetted on both sides", "Low fees + fast payout", "Built-in disputes + ratings"],
      price_positioning: "fair-fee",
      personality_traits: ["trustworthy", "transparent", "growth-stage but credible"],
      words_to_use: ["vetted", "fast payout", "rated 4.9/5", "no surprise fees"],
      words_to_avoid: ["disruptive", "revolution", "platform"],
      best_performing_angles: ["seller success stories", "buyer save-money math", "behind-the-vetting"],
    }),
  },
  {
    slug: "real_estate",
    name: "Real estate (agent / broker)",
    emoji: "🏠",
    description: "Lead gen for buyers + sellers. Local + reputation-driven.",
    apply: (o) => makeBrain(o, {
      industry: "Real estate",
      tone: "Trusted neighbor, not slick sales.",
      writing_style: "Plain English. Mentions the neighborhood. Cites real data.",
      audience_who: "Buyers + sellers in a 10-mile zone, 30-65, often first-time or move-up.",
      audience_pain_points: ["Don't trust the process", "Worry about market timing", "Burned by past agent"],
      audience_desires: ["Local pro who knows THIS neighborhood", "Honest market read", "Smooth transaction"],
      key_benefits: ["Closed X homes in [neighborhood] last year", "Average days-on-market 30% below area average", "Weekly market report — free to subscribers"],
      price_positioning: "standard commission, premium service",
      personality_traits: ["neighborly", "data-fluent", "low-pressure"],
      words_to_use: ["in [neighborhood]", "closed this year", "honest market read", "I'll send you"],
      words_to_avoid: ["luxury", "best agent", "top 1%"],
      best_performing_angles: ["neighborhood-specific market data", "first-time-buyer how-to", "behind-the-listing tour"],
    }),
  },
];

export function applyTemplate(slug: string, override: { business_name?: string; website_url?: string }): BrandBrain | null {
  const t = INDUSTRY_TEMPLATES.find((x) => x.slug === slug);
  if (!t) return null;
  return t.apply(override);
}
